WIP: Sign up
CraftAcademy/homechef pull request #12
Opened 2017-01-15 18:46 UTC by rmzse

## Pivotal Tracker story 

https://www.pivotaltracker.com/story/show/137254137

## Changes proposed in this pull request:

This feature creates the sign up functionality to enable users to sign up and create a user account in the system.

## What I have learned working on this feature:

• recapping TDD and acceptance testing
• installing and setting up Devise
• validating models and factories

#### Ready for review!

2017-01-25 12:52 UTC, tochman commented
There are merge conflicts here. When will this be worked on?

2017-01-25 12:56 UTC, tochman requested changes

2017-01-25 12:56 UTC, tochman commented on app/models/user.rb
> +  validates :last_sign_in_ip, presence: true
None of this validations are needed. Please stick to the Devise documentation

2017-01-25 12:56 UTC, tochman commented on features/step_definitions/assertion_steps.rb
> +# end
Get rid of comments please

2017-01-25 12:56 UTC, tochman commented on features/step_definitions/sign_up_steps.rb
> +end
Pleas fix settings on the IDE/editor to properly format code.

2017-01-25 12:56 UTC, tochman commented on spec/factories/users.rb
> +    last_sign_in_ip '127.0.0.0'
Most of these settings are not needed. Please see comment about validations

2017-01-25 12:56 UTC, tochman commented on spec/models/user_spec.rb
> +    end
No need to validate most of these attributes. Devise takes care of most of that.

2017-01-25 15:30 UTC, diraulo reviewed
@rmzse @kriizjones Are you guys overriding any of the Devise views with your own content/styles? If not then all the Devise generated views are not necessary and can be deleted.

Also, I'm afraid this PR is seriously growing out of scope. Creating a PR template really has nothing to do with User Signup for example.

2017-01-25 16:20 UTC, tochman requested changes

2017-01-25 16:20 UTC, tochman commented on README.md
> +We are using Travis for continous integration and Heroku for deployment.
Why on earth are you including the README updates in this PR? Please remove this.

2017-01-25 17:03 UTC, rmzse commented on features/step_definitions/sign_up_steps.rb
> +end
@tochman we are not finding this err, as Rubymine says it's already fixed. We'll try one more thing and see if we succeed.

![image](https://cloud.githubusercontent.com/assets/13518870/22300665/76808710-e328-11e6-9bbc-85f89dbc7bf5.png)

2017-01-25 19:03 UTC, tochman requested changes
Much better, almost there.

2017-01-25 19:03 UTC, tochman commented on features/sign_up.feature
> +    Then I should be on the "Sign up" page
We spoke about assertions like this in our last session. Please remove this.

2017-01-26 05:04 UTC, rmzse commented on features/sign_up.feature
> +    Then I should be on the "Sign up" page
Yes, we did! 
Sorry, forgot this one in the midst of everything else...

2017-01-26 09:03 UTC, rmzse commented on features/sign_up.feature
> +    Then I should be on the "Sign up" page
@tochman Code review please! :)

2017-01-26 09:04 UTC, tochman commented on features/sign_up.feature
> +    Then I should be on the "Sign up" page
Why is this step still here?

2017-01-26 09:04 UTC, tochman commented on spec/models/user_spec.rb
> +
Remove empty lines please.

2017-01-26 10:16 UTC, tochman commented
Still WIP? Please fix conflicts.

2017-01-26 11:53 UTC, tochman approved these changes

2017-01-26 11:53 UTC, merged