Update README file
CraftAcademy/homechef pull request #15
Opened 2017-01-25 16:00 UTC by aniansson

## Pivotal Tracker:
https://www.pivotaltracker.com/story/show/137600399

## Changes proposed in this pull request:
Updated changes and descriptions in file.

## What I have learned working on this feature: 
To not make changes directly on Github, to not branch off on Github, to not repeat mistake and to learn from mistakes. As well as updating and giving better descriptions in README files. And what should be included. 

Ready for review!

2017-01-25 16:05 UTC, tochman requested changes

2017-01-25 16:05 UTC, tochman commented on README.md
> +$rake
Add space
```
$ rake
```

2017-01-25 16:05 UTC, tochman commented on README.md
> +We are using Travis for continous integration and Heroku for deployment
I would like you to add instructions on how the app can be deployed.

2017-01-25 16:05 UTC, tochman commented on README.md
I would like you to list the technologies used in this application.

2017-01-25 16:42 UTC, aniansson commented on README.md
> +$rake
What do you mean?

2017-01-25 16:43 UTC, aniansson commented on README.md
> +We are using Travis for continous integration and Heroku for deployment
Do you mean entire instructions for ho to install etc?

2017-01-26 08:36 UTC, tochman approved these changes

2017-01-26 09:07 UTC, merged