Log in
CraftAcademy/homechef pull request #17
Opened 2017-01-26 13:57 UTC by kriizjones

# Pivotal Tracker story

www.pivotaltracker.com/n/projects/1948009

Changes proposed in this pull request:

This feature create the Log in functionality to enable users to log in 

# What I have learned working on this feature:

• recapping TDD and acceptance testing
• installing and setting up Devise
• more about step definitions

Ready for review!

2017-01-26 14:44 UTC, AmberWilkie requested changes

2017-01-26 14:44 UTC, AmberWilkie commented on config/environments/development.rb
> +  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
This line should not be uncommented. I know Devise told you to do it, but we're not using mailers.

2017-01-26 14:44 UTC, AmberWilkie commented on features/log_in.feature
> +  Scenario: Visitor logs in so them can create a dish to sell or they can buy a dish
`Scenario: A user logs in`

2017-01-26 14:44 UTC, AmberWilkie commented on features/log_in.feature
> +    And I should see "Signed in successfully."
```
And I click "Log in" button
Then I should be on the "Landing" page
And I should see "Signed in successfully."
```

2017-01-26 14:44 UTC, AmberWilkie commented on spec/factories/models.rb
> +end
Delete this file.

2017-01-26 14:50 UTC, tochman commented
The commit history on this PR is messed up. We need to create feature branches from develop. This needs to be cherry-picked. Not cool.

2017-01-26 14:50 UTC, tochman requested changes
Fix commit history

2017-01-26 17:56 UTC, kriizjones commented on config/environments/development.rb
> +  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
done.

2017-01-26 17:57 UTC, kriizjones commented on features/log_in.feature
> +  Scenario: Visitor logs in so them can create a dish to sell or they can buy a dish
done.

2017-01-26 17:59 UTC, kriizjones commented on features/log_in.feature
> +    And I should see "Signed in successfully."
done . :)

2017-01-26 18:01 UTC, kriizjones commented on spec/factories/models.rb
> +end
done, deleted!

2017-01-26 18:37 UTC, tochman requested changes

2017-01-26 18:37 UTC, tochman commented on features/log_in.feature
> +  So I can sell or buy dishes
Please use proper user story format. Update the tracker as well.

2017-01-26 18:37 UTC, tochman commented on features/log_in.feature
> +
Remove extra line break

2017-01-26 18:37 UTC, tochman commented on features/step_definitions/basic_steps.rb
> +
Remove extra line break.

2017-01-26 19:54 UTC, kriizjones commented on features/step_definitions/basic_steps.rb
> +
done.

2017-01-26 19:55 UTC, kriizjones commented on features/log_in.feature
> +
done.

2017-01-26 19:59 UTC, kriizjones commented on features/log_in.feature
> +  So I can sell or buy dishes
done.

2017-01-26 20:07 UTC, tochman commented
The commit history is a big obstacle for me to be honest. Bit I'm willing to let this go. I will monitor your next PR and I hope you are more on top of things next time.

2017-01-26 20:07 UTC, tochman approved these changes

2017-01-27 08:39 UTC, AmberWilkie approved these changes

2017-01-27 08:40 UTC, merged