Edit profile user
CraftAcademy/homechef pull request #24
Opened 2017-02-02 18:35 UTC by kriizjones

## Pivotal Tracker story 

https://www.pivotaltracker.com/n/projects/1948009

## Changes proposed in this pull request:

This feature : When I sign up so there is a page, come up for edit your info. Its include
email, password, first name, last name, address, zip code, city, phone number and if you want to change password. 

## What I have learned working on this feature:

• Better to understand and learn the sad path!

#### Ready for review!

2017-02-03 12:11 UTC, tochman requested changes

2017-02-03 12:11 UTC, tochman commented on app/controllers/registrations_controller.rb
> +  end
You can remove all these 3 methods now. They are not needed. Make sure you run all tests before you push up.

2017-02-03 12:21 UTC, kriizjones commented on app/controllers/registrations_controller.rb
> +  end
Oh srry about that, deleted done. 
yes i will !

2017-02-04 12:25 UTC, tochman approved these changes

2017-02-04 12:25 UTC, merged