WIP Display user profile
CraftAcademy/homechef pull request #26
Opened 2017-02-04 14:48 UTC by aniansson

## Pivotal Tracker story 

https://www.pivotaltracker.com/story/show/138269297

## Changes proposed in this pull request:

Displays the user profile

## What I have learned working on this feature:
The basic skills of rails, routes, controllers

#### Ready for review!

2017-02-04 18:38 UTC, aniansson commented
Review and merge _**"Add dish to my dishes"**_ code first!!! Test failing due to missing stuff from that branch.

2017-02-04 19:02 UTC, tochman commented
I ❤️ HAML

2017-02-06 15:03 UTC, tochman requested changes

2017-02-06 15:03 UTC, tochman commented on app/views/checkout/index.html.erb
> +                    <h5 class="media-heading">
This way of naming the internal link seems odd. I will let this pass but `#dish2Modal` feels weird. We don't use camel case in Id's or anchor links

2017-02-06 15:03 UTC, tochman commented on features/display_user_profile.feature
> +    When I am on the "landing" page
Given. It should be Given

2017-02-06 15:03 UTC, tochman commented on features/display_user_profile.feature
> +    And I should see "Successfully added 5 portions of Meatballs at $59.99 each to your dishes"
Then. Are you guys reading your own scenarios?

2017-02-06 15:03 UTC, tochman commented on features/display_user_profile.feature
> +    And I should see "18:00"
Way too long scenario.

2017-02-06 15:03 UTC, tochman commented on features/step_definitions/display_dishes_steps.rb
> +  @dish.save
I would do this. More readible
```
user = User.find_by(username: "Philippo")
@dish.update_attribute(user: user)
```

2017-02-06 15:26 UTC, Philippoes commented on app/views/checkout/index.html.erb
> +                    <h5 class="media-heading">
Gotcha

2017-02-06 16:39 UTC, tochman approved these changes

2017-02-06 16:39 UTC, merged