Feature: Display Dishes
CraftAcademy/homechef pull request #3
Opened 2017-01-10 16:17 UTC by aniansson

## Pivotal: 
https://www.pivotaltracker.com/story/show/137256347

## Changes proposed in this pull request:
Created dish model in database and generated controller for dish. Plus route for page. Creates a global variable for all dishes and passes them to the dish view where all of them are displayed. Plus made Rspec test.

## What I have learned working on this feature: 
Repetition on creating and generating models, making Rspec test. So refreshing for mind.

NOT READY FOR REVIEW

2017-01-10 16:30 UTC, tochman reviewed
Good job so far. Will review when time comes. 😜

2017-01-10 17:26 UTC, AmberWilkie requested changes
Think about this show vs. index thing. If Thomas told you to use show and you're planning to change it later or not provide any individual dish information, no problem.

2017-01-10 17:26 UTC, AmberWilkie commented on features/display_dishes.feature
> +    |   taco    |    really spicy authentic Mexican tacos                         |    59   |   16:00   |    10    |
No one in this country is making authentic tacos, but not a blocker.

2017-01-10 17:26 UTC, AmberWilkie commented on config/routes.rb
> +  get 'dishes/show'
Should this really be the show page? We normally use that for individual dishes. This is the kind of info we would ordinarily put in an index for dishes. So url.com/dishes takes you to a list of all dishes and when you want to view an individual dish, it's url.com/dishes/1 - and that's what the `show` method is for.

2017-01-10 17:26 UTC, AmberWilkie commented on config/routes.rb
> +  get 'dishes/show'
Either way, there's better Rails syntax for this. we can do:
`resources :dishes, only: [:show]` and that should give you the same routes you have now, plus a helper.

2017-01-10 18:03 UTC, AmberWilkie approved these changes
Looks great!

2017-01-10 18:04 UTC, tochman requested changes

2017-01-10 18:04 UTC, tochman commented on app/models/dish.rb
> +  validates :portions, presence: true
I would suggest using
```
validates_presence_of : name, :description, etc...
```
= less code. What do you think?

2017-01-10 18:04 UTC, tochman commented on app/views/dishes/index.html.erb
> +    </li>
Mind the code indentation...

2017-01-10 18:04 UTC, tochman commented on features/display_dishes.feature
> +    |   taco    |    really spicy authentic Mexican tacos                         |    59   |   16:00   |    10    |
Also, I can't see that you are testing for the presence of `tacos`. If not used, why is it added to the db`

2017-01-10 18:04 UTC, tochman commented on features/step_definitions/basic_steps.rb
> +When(/^I am on the landing page$/) do
Is the `dishes_path` really the `landing page`? It seems to conflict with the story the other team is working on.

2017-01-10 18:04 UTC, tochman commented on features/step_definitions/basic_steps.rb
> +end
I always prefer to separate the step definition that are assertions into a separate file for better readability.

2017-01-10 18:04 UTC, tochman commented on spec/factories/dishes.rb
> +    readytime "2017-01-10 16:32:43"
Not a blocker but I would be mindful on how this value is set. I would prefer `Date.today (or .now or whatever..)` Also, I would consider validating that the `readytime` is in the future. (I also have a problem with the attribute itself, `readytime` does not feel like a good name. I would at least separate the words with an underscore `ready_time`)

2017-01-10 18:04 UTC, tochman commented on spec/models/dish_spec.rb
> +  describe "Validation" do
`Validation` or `Validations`? Are we testing one or several validations?

2017-01-10 18:04 UTC, tochman commented on spec/models/dish_spec.rb
> +  describe "DB table" do
Are we testing one or several tables?

2017-01-10 18:23 UTC, Philippoes commented on features/step_definitions/basic_steps.rb
> +When(/^I am on the landing page$/) do
We are changing this when landing page is merged. We are adding the dishes as a partial to the landing page. That's why it says landing

2017-01-10 18:23 UTC, Philippoes commented on features/display_dishes.feature
> +    |   taco    |    really spicy authentic Mexican tacos                         |    59   |   16:00   |    10    |
Yes, we totally missed that. Fixing asap.

2017-01-10 18:23 UTC, tochman commented on features/step_definitions/basic_steps.rb
> +When(/^I am on the landing page$/) do
Okay, thank you for the clarification.

2017-01-10 20:27 UTC, tochman commented on app/views/dishes/index.html.erb
> +    </li>
Still not formatted correctly. There's a auto format tool in RubyMine.

2017-01-10 20:37 UTC, tochman commented on spec/models/dish_spec.rb
> +    it { is_expected.to have_db_column :ready_time }
You need to add a migration to rename that attribute in order to make these tests to pass.

2017-01-10 20:45 UTC, tochman approved these changes

2017-01-11 12:32 UTC, tochman requested changes

2017-01-11 12:32 UTC, tochman commented on features/step_definitions/display_dishes_steps.rb
> +  end
Please use a case statement here. Much cleaner

2017-01-11 12:55 UTC, tochman approved these changes

2017-01-11 13:00 UTC, merged