WIP: Main landing page
CraftAcademy/homechef pull request #4
Opened 2017-01-10 18:16 UTC by rmzse

## Pivotal Tracker story 

https://www.pivotaltracker.com/story/show/137256271

## Changes proposed in this pull request:

This feature creates the main landing page

## What I have learned working on this feature:

WIP, pending. Recap of the basic cycle of routes, controllers and views.

#### Ready for review!

2017-01-10 18:17 UTC, rmzse commented
@Philippoes @aniansson pls review and approve in order to continue your work!

2017-01-10 18:21 UTC, aniansson approved these changes

2017-01-10 18:49 UTC, Philippoes approved these changes
Looks good!

2017-01-10 23:08 UTC, rmzse commented
@Philippoes @aniansson now this is ready to merge!

2017-01-11 06:41 UTC, tochman commented on app/views/landing/index.html.erb
> +<%= content_tag(:div, "Logotype", id: ["logotype"]) %>
Why is the `id:` wrapped in hard brackets?

2017-01-11 06:43 UTC, tochman commented on features/step_definitions/assertion_steps.rb
> +	%q{ When I visit the main landing page }
No, no, no... we don't mix assertions with interaction commands

2017-01-11 06:43 UTC, tochman requested changes
See comments....

2017-01-11 08:49 UTC, rmzse commented on app/views/landing/index.html.erb
> +<%= content_tag(:div, "Logotype", id: ["logotype"]) %>
According to the finders dox that's the way to do it, but removing them works fine too. =)

2017-01-11 09:01 UTC, tochman commented on features/main_landing_page.feature
> +    And I should see a placeholder for dishes in general with an id of "random_dishes"
I would use `I should see a "random_dishes" placeholder`. This feels like a duplicate.

2017-01-11 10:52 UTC, rmzse commented
@tochman code review pls!

2017-01-11 10:55 UTC, AmberWilkie commented on features/main_landing_page.feature
> +    And I should see a link called "Home"
This step is totally unnecessary, considering you're clicking the link in the next step.

2017-01-11 10:57 UTC, AmberWilkie commented on features/step_definitions/assertion_steps.rb
> +end
Dudes. It doesn't have to be this way. If you insist on having different wording, you can do instead:
`I should (?: go to | be on) the main landing page` and then the content of the step is the same.

2017-01-11 10:58 UTC, AmberWilkie commented on features/step_definitions/main_landing_page_steps.rb
> +  %q{ I visit the main landing page }
No no no. If you click the link and it takes you to the main landing page, then you should be on the main landing page. You're clicking a link and then redirecting in the same step.

2017-01-11 10:58 UTC, rmzse commented on features/main_landing_page.feature
> +    And I should see a link called "Home"
Yes, we had the link and the click of it in one statement before, but were required to split them. Should we omit the naming of the link we are clicking altogether? How can we make sure it is THAT specific one link that leads us to that specific page?

2017-01-11 10:59 UTC, rmzse commented on features/step_definitions/assertion_steps.rb
> +end
Great stuff! Let's change that IMMEDIATELY.

2017-01-11 11:00 UTC, AmberWilkie commented
You are already testing that the link exists, simply by clicking it. If
there's no link, Cucumber will say "link not found" or whatever. You don't
have to directly test that there is a link (vs. text).


*Amber Wilkie*
www.amberwilkie.com
0720.08.27.07 | Instagram <http://www.instagram.com/amberwphoto>


On Wed, Jan 11, 2017 at 11:58 AM, rmzse <notifications@github.com> wrote:

> *@rmzse* commented on this pull request.
> ------------------------------
>
> In features/main_landing_page.feature
> <https://github.com/CraftAcademy/homechef/pull/4>:
>
> > @@ -0,0 +1,14 @@
> +Feature: Main landing page
> +  As a visitor
> +  In order to get an overview over the service
> +  I need to see a main landing page
> +
> +  Scenario: Visitor visits main page
> +    When I visit the main landing page
> +    Then I should see "Welcome to HomeChef"
> +    And I should see input of type "text" with name "enter_location"
> +    And I should see a "general_random_dishes" placeholder
> +    And I should see a "logotype" placeholder
> +    And I should see a link called "Home"
>
> Yes, we had the link and the click of it in one statement before, but were
> required to split them. Should we omit the naming of the link we are
> clicking altogether? How can we make sure it is THAT specific one link that
> leads us to that specific page?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/CraftAcademy/homechef/pull/4>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATNVdBhjrwGcuFWe91Z9NlH7oLdhzzbAks5rRLXFgaJpZM4Lfuvx>
> .
>

2017-01-11 11:00 UTC, AmberWilkie commented on features/main_landing_page.feature
> +    And I should see a link called "Home"
You do not have to test that the link is on the page if you are clicking the link. If there was no link, you couldn't click it.

2017-01-11 11:11 UTC, rmzse commented on features/step_definitions/assertion_steps.rb
> +end
That solution did not work for us, we simplify it and keep two statements for visiting root path.

2017-01-11 11:15 UTC, rmzse commented
@AmberWilkie code review pls!

2017-01-11 11:27 UTC, tochman approved these changes

2017-01-11 11:27 UTC, AmberWilkie approved these changes
Much better!

2017-01-11 11:54 UTC, merged